### ISSUE TITLE
Position not mandatory for animation: steps

### ISSUE THREAD

**Issue by zeroby0** [hookhookun/parse-animation-shorthand#20]
https://github.com/hookhookun/parse-animation-shorthand/blob/2a54be6c659115bced4f198d90fe7e3be884711b/src/getSteps.ts#L24-L26

Position is not mandatory for steps  ([spec](https://www.w3.org/TR/css-easing-1/#funcdef-step-easing-function-steps), [demo](https://codepen.io/Guilh/pen/MWOwBL)).

There's code out in the wild that doesn't use position: https://github.com/ForkAwesome/Fork-Awesome/issues/404, which can't be properly parsed and raises the error.

---

Thank you for creating this module! It's being used by subfont which a lot of people depend on, I'd like to thank you on behalf of everyone :))

https://github.com/Munter/subfont/blob/186179518b5d93dad02abeed3396d1ea59e95351/package.json#L50

**Comment by hookhookun** [comment]
Sorry for the late reply. I'll check it within the next two weeks and correct it if necessary.
Thank you for your report and kind words.

**Comment by zeroby0** [comment]
Thank you. Please take your time.

**Comment by hookhookun** [comment]
I've fixed the bug and have released [v0.1.5](https://github.com/hookhookun/parse-animation-shorthand/releases/tag/v0.1.5) with the fix.
Thank you for reporting the issue.

**Comment by zeroby0** [comment]
Thank you so much! Hope you have an amazing new year ahead!
